import { mutation } from "./_generated/server";

export const seed = mutation({
    args: {},
    handler: async (ctx) => {
        const existing = await ctx.db.query("templates").first();
        if (existing) return { status: "already_seeded" };

        const now = new Date().toISOString();
        const templates = [
            {
                name: "Mission Commander",
                slug: "mission-commander",
                description: "Central orchestrator that breaks down goals into tasks, delegates to specialists, and tracks progress.",
                longDescription: "The Mission Commander is a master orchestrator agent. Give it a high-level goal and it will:\n\n1. Analyze the goal and break it into actionable tasks\n2. Identify which specialist agents are needed\n3. Delegate tasks with clear instructions\n4. Monitor progress and handle blockers\n5. Report final results\n\nPerfect as the brain of your agent team.",
                category: "orchestrator" as const,
                icon: "🧠",
                color: "#7c5cfc",
                systemPrompt: "You are Mission Commander — a master orchestrator AI. You receive high-level goals, break them into tasks, assign them to specialists, and track progress.",
                defaultModel: "gpt-4o",
                tags: ["orchestrator", "planning", "delegation", "tracking"],
                authorId: "system",
                authorName: "OpenClaw Team",
                version: "1.0.0",
                downloads: 2847,
                stars: 342,
                isVerified: true,
                isFeatured: true,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Pipeline Conductor",
                slug: "pipeline-conductor",
                description: "Sequential workflow orchestrator for multi-step pipelines with handoffs and error recovery.",
                category: "orchestrator" as const,
                icon: "🎬",
                color: "#00d4ff",
                systemPrompt: "You are Pipeline Conductor — a workflow orchestrator for sequential pipelines.",
                defaultModel: "gpt-4o",
                tags: ["orchestrator", "workflow", "pipeline", "sequential"],
                authorId: "system",
                authorName: "OpenClaw Team",
                version: "1.0.0",
                downloads: 1563,
                stars: 198,
                isVerified: true,
                isFeatured: false,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Code Architect",
                slug: "code-architect",
                description: "Senior software engineer. Writes production code, designs systems, reviews PRs, and debugs issues.",
                category: "specialist" as const,
                icon: "💻",
                color: "#34d399",
                systemPrompt: "You are Code Architect — a senior software engineer. Write production-quality code with tests and docs.",
                defaultModel: "claude-3.5-sonnet",
                tags: ["coding", "architecture", "debugging", "review"],
                authorId: "system",
                authorName: "OpenClaw Team",
                version: "1.2.0",
                downloads: 4210,
                stars: 567,
                isVerified: true,
                isFeatured: true,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Research Analyst",
                slug: "research-analyst",
                description: "Deep researcher that gathers, synthesizes, and presents information from multiple sources.",
                category: "specialist" as const,
                icon: "🔍",
                color: "#60a5fa",
                systemPrompt: "You are Research Analyst — a thorough researcher. Cross-reference sources, present structured reports.",
                defaultModel: "gpt-4o",
                tags: ["research", "analysis", "reports", "fact-checking"],
                authorId: "system",
                authorName: "OpenClaw Team",
                version: "1.1.0",
                downloads: 3120,
                stars: 421,
                isVerified: true,
                isFeatured: true,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Content Writer",
                slug: "content-writer",
                description: "Versatile writer for blogs, docs, marketing copy, tweets, and technical writing.",
                category: "specialist" as const,
                icon: "✍️",
                color: "#f59e0b",
                systemPrompt: "You are Content Writer — craft compelling content for any medium. Match brand voice, optimize for audience.",
                defaultModel: "claude-3.5-sonnet",
                tags: ["writing", "content", "marketing", "docs"],
                authorId: "community",
                authorName: "Agent Builder",
                version: "2.0.0",
                downloads: 2890,
                stars: 312,
                isVerified: false,
                isFeatured: false,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "QA Inspector",
                slug: "qa-inspector",
                description: "Quality assurance specialist. Reviews work, finds edge cases, writes test plans.",
                category: "specialist" as const,
                icon: "🔬",
                color: "#f87171",
                systemPrompt: "You are QA Inspector — review deliverables, find bugs, write comprehensive test plans.",
                defaultModel: "gpt-4o",
                tags: ["testing", "quality", "review", "validation"],
                authorId: "system",
                authorName: "OpenClaw Team",
                version: "1.0.0",
                downloads: 1890,
                stars: 213,
                isVerified: true,
                isFeatured: false,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Data Cruncher",
                slug: "data-cruncher",
                description: "Data analysis and visualization. Processes datasets, builds models, extracts insights.",
                category: "specialist" as const,
                icon: "📊",
                color: "#a78bfa",
                systemPrompt: "You are Data Cruncher — process datasets, perform analysis, build models, create visualizations.",
                defaultModel: "gpt-4o",
                tags: ["data", "analytics", "visualization", "ml"],
                authorId: "community",
                authorName: "DataWiz",
                version: "1.3.0",
                downloads: 1245,
                stars: 167,
                isVerified: false,
                isFeatured: false,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "API Connector",
                slug: "api-connector",
                description: "Integration specialist. Connects APIs, transforms data, handles authentication flows.",
                category: "integration" as const,
                icon: "🔌",
                color: "#14b8a6",
                systemPrompt: "You are API Connector — integrate external APIs, handle auth, transform data between services.",
                defaultModel: "gpt-4o",
                tags: ["api", "integration", "rest", "webhooks"],
                authorId: "system",
                authorName: "OpenClaw Team",
                version: "1.0.0",
                downloads: 987,
                stars: 134,
                isVerified: true,
                isFeatured: false,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Workflow Automator",
                slug: "workflow-automator",
                description: "Designs and executes automated workflows. Triggers, conditions, loops, and error handling.",
                category: "workflow" as const,
                icon: "⚡",
                color: "#eab308",
                systemPrompt: "You are Workflow Automator — design automated workflows with triggers, conditions, and error handling.",
                defaultModel: "gpt-4o",
                tags: ["workflow", "automation", "triggers", "scheduling"],
                authorId: "community",
                authorName: "AutoBot",
                version: "1.1.0",
                downloads: 1567,
                stars: 189,
                isVerified: false,
                isFeatured: true,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Summarizer",
                slug: "summarizer",
                description: "Condenses long texts, meetings, and documents into actionable summaries.",
                category: "utility" as const,
                icon: "📋",
                color: "#9ca3af",
                systemPrompt: "You are Summarizer — produce clear, structured summaries. Highlight key decisions and action items.",
                defaultModel: "gpt-4o-mini",
                tags: ["summarization", "condensing", "notes"],
                authorId: "system",
                authorName: "OpenClaw Team",
                version: "1.0.0",
                downloads: 3456,
                stars: 245,
                isVerified: true,
                isFeatured: false,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Translator Pro",
                slug: "translator-pro",
                description: "Multi-language translation preserving tone, context, and cultural nuance.",
                category: "utility" as const,
                icon: "🌐",
                color: "#2dd4bf",
                systemPrompt: "You are Translator Pro — translate while preserving meaning, tone, and cultural nuance.",
                defaultModel: "gpt-4o",
                tags: ["translation", "languages", "localization"],
                authorId: "community",
                authorName: "LinguaBot",
                version: "2.1.0",
                downloads: 2134,
                stars: 278,
                isVerified: false,
                isFeatured: false,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: "Email Composer",
                slug: "email-composer",
                description: "Drafts professional emails with perfect tone, structure, and call-to-actions.",
                category: "utility" as const,
                icon: "📧",
                color: "#f472b6",
                systemPrompt: "You are Email Composer — draft professional emails. Match formality level, include clear CTAs.",
                defaultModel: "gpt-4o-mini",
                tags: ["email", "communication", "professional"],
                authorId: "community",
                authorName: "MailCraft",
                version: "1.0.0",
                downloads: 1678,
                stars: 145,
                isVerified: false,
                isFeatured: false,
                createdAt: now,
                updatedAt: now,
            },
        ];

        // Seed categories
        const categories = [
            { name: "Orchestrators", slug: "orchestrator", description: "Master coordinators that manage agent teams", icon: "🧠", color: "#7c5cfc", templateCount: 2 },
            { name: "Specialists", slug: "specialist", description: "Expert agents for specific domains", icon: "⚡", color: "#FF6B6B", templateCount: 4 },
            { name: "Utilities", slug: "utility", description: "General-purpose helper agents", icon: "🔧", color: "#FFD93D", templateCount: 3 },
            { name: "Workflows", slug: "workflow", description: "Process automation agents", icon: "🔄", color: "#eab308", templateCount: 1 },
            { name: "Integrations", slug: "integration", description: "API and service connectors", icon: "🔌", color: "#14b8a6", templateCount: 1 },
        ];

        for (const t of templates) await ctx.db.insert("templates", t);
        for (const c of categories) await ctx.db.insert("categories", c);

        return { status: "seeded", templates: templates.length, categories: categories.length };
    },
});
